# Generated by Django 3.0.4 on 2020-03-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20200314_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CategoryImage',
            field=models.ImageField(blank=True, upload_to='assets/images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
