# Generated by Django 3.0.4 on 2020-03-16 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20200314_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='images/')),
                ('parent_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image')),
            ],
        ),
    ]
