# Generated by Django 3.0.4 on 2020-03-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
